// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsnwruwxwbhnfdmuoqcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbndydXd4d2JobmZkbXVvcWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzEyMDQsImV4cCI6MjA2MzQwNzIwNH0.iFXMlz-c0lRAow3nh7xThpRCoj06Rf_9-vumsO7rizY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);